### ISSUE TITLE
bootstrap 4.0.0 or 3.3.7 dependency

### ISSUE THREAD

**Issue by Oliverwong369** [Oliverwong369/AstroCraftPlus#13]
new feature or stable?

**Comment by Oliverwong369** [comment]
@Oliverwong123 @Oliverwong347

**Comment by Oliverwong123** [comment]
Bootstrap4 stable version has been released now.
I suggest using 4 stable version, though have to spend more time in w3schools.  >_< #

**Comment by Oliverwong369** [comment]
I agree with witcher.
Stable version 4.0.0 is ok. @Oliverwong347

**Comment by Oliverwong347** [comment]
Alright, I'll **close the #12**  pull request and push a new commit A.S.A.P.
@Oliverwong369 @Oliverwong123

**Comment by Oliverwong369** [comment]
@Oliverwong347 Great!
