### ISSUE TITLE
Hand Gesture Recognition for Mobile Devices

### ISSUE THREAD

**Issue by Oliverwong347** [Oliverwong369/AstroCraftPlus#25]
### Our post editor is supposed to recognize gesture for mobile devices. 
Are there any libraries to solve the problem? @Oliverwong369 @Oliverwong123
[Hammer.js](https://hammerjs.github.io/getting-started/) seems to be a popular library.

**Comment by Oliverwong369** [comment]
Hammer.JS behaves very well on mobile devices.

**Comment by Oliverwong123** [comment]
Angular make it really easy to integrate with HammerJS for touch gesture event detection. That's it.

**Comment by Oliverwong369** [comment]
Happy coding! @Oliverwong347 🐼🔥

**Comment by Oliverwong347** [comment]
Got it.
