### ISSUE TITLE
Lazy-Loading Modules

### ISSUE THREAD

**Issue by Oliverwong123** [Oliverwong369/AstroCraftPlus#28]
Obviously, too many modules are included in the initial module (app module).
Angular appears to be quite heavy especially on mobile.
It is possible to lazy-load modules by using the **loadChildren** property.

**Comment by Oliverwong369** [comment]
From the user perspective I agree with spliting our application in modules to reduce loading times.
We can do more with modules, than just organizing our components.

**Comment by Oliverwong347** [comment]
Exactly.

**Comment by Oliverwong123** [comment]
Ok. I'll create a new pull request. @Oliverwong369 @Oliverwong347
