### ISSUE TITLE
Update our project from Angular 4 to Angular 5

### ISSUE THREAD

**Issue by Oliverwong123** [Oliverwong369/AstroCraftPlus#31]
Angular 5 is awesome, it's faster and smaller. @Oliverwong369 @Oliverwong347 
Updating our Angular 4 app to Angular 5 is unlikely to introduce any frustrating breaking changes. 
[Version 5.0.0 of Angular Now Available](url)
[https://github.com/angular/angular/blob/master/CHANGELOG.md](url)

BTW: It seem to be safe to use **@ angular/material** (which is based on Angular 5) in an Angular project. We can switch to angular 5 to avoid any issues.

**Comment by Oliverwong369** [comment]
Exactly. It‘s faster, lighter and easy to use. Apart from this, it added Material Design compatibilities.
I agree with updating our application to Angular 5. 🌟🌟🌟

**Comment by Oliverwong347** [comment]
I found this [guide](https://angular-update-guide.firebaseapp.com/) to tell us the steps to update.
@Oliverwong123

**Comment by Oliverwong123** [comment]
Thanks, this is exactly what I was looking for. 👍 @Oliverwong347 
Ok. I'll create a new pull request. @Oliverwong369
